# Generated by Django 6.0.2 on 2026-02-27 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X / Twitter'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, help_text='Custom label (optional)', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
    ]
