# Generated by Django 6.0.2 on 2026-02-27 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, help_text='e.g. $25, From $100, Free', max_length=50)),
                ('image', models.ImageField(upload_to='catalog/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
