# Generated by Django 6.0.2 on 2026-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_catalogcategory_catalogitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color_bg',
            field=models.CharField(blank=True, default='#F8FAFB', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_btn',
            field=models.CharField(blank=True, default='#2EC4B6', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_btn_text',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_primary',
            field=models.CharField(blank=True, default='#2EC4B6', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_secondary',
            field=models.CharField(blank=True, default='#6B2FA0', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_text',
            field=models.CharField(blank=True, default='#1E293B', max_length=7),
        ),
    ]
