# Generated by Django 6.0.2 on 2026-02-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='profiles.catalogitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
