# Generated by Django 6.0.2 on 2026-02-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_add_catalog_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_bio',
            field=models.BooleanField(default=True, help_text='Show About / Bio section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_business_hours',
            field=models.BooleanField(default=False, help_text='Show business hours section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_catalog',
            field=models.BooleanField(default=True, help_text='Show Products / Catalog section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_contact_form',
            field=models.BooleanField(default=False, help_text='Show a contact form on profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Show phone, email, location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_gallery',
            field=models.BooleanField(default=False, help_text='Show photo gallery section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_services',
            field=models.BooleanField(default=False, help_text='Show services section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_skills',
            field=models.BooleanField(default=False, help_text='Show skills / expertise section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_social_links',
            field=models.BooleanField(default=True, help_text='Show social media links'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_testimonials',
            field=models.BooleanField(default=False, help_text='Show testimonials / reviews'),
        ),
    ]
