# Generated by Django 6.0.2 on 2026-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_show_bio_profile_show_business_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_back_image',
            field=models.ImageField(blank=True, help_text='Photo of the back of your NFC card', upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_front_image',
            field=models.ImageField(blank=True, help_text='Photo of the front of your NFC card', upload_to='cards/'),
        ),
    ]
