# Generated by Django 6.0.2 on 2026-03-01 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_card_back_image_profile_card_front_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.CharField(blank=True, help_text='e.g. $50/hr, From $200, Free consultation', max_length=50)),
                ('icon', models.CharField(choices=[('briefcase', 'Briefcase'), ('code', 'Code'), ('paint', 'Design'), ('camera', 'Photography'), ('chart', 'Analytics'), ('globe', 'Web'), ('megaphone', 'Marketing'), ('wrench', 'Maintenance'), ('shield', 'Security'), ('heart', 'Health'), ('book', 'Education'), ('truck', 'Delivery'), ('home', 'Real Estate'), ('music', 'Music'), ('film', 'Video'), ('star', 'Premium'), ('zap', 'Lightning'), ('users', 'Consulting')], default='briefcase', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
