# Generated by Django 6.0.2 on 2026-03-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_gallery_businesshours_testimonials_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='map_location_label',
            field=models.CharField(blank=True, help_text='Friendly address shown on the map', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_map',
            field=models.BooleanField(default=False, help_text='Show location map on profile'),
        ),
    ]
