# Generated by Django 6.0.2 on 2026-03-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_map_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_website_portfolio',
            field=models.BooleanField(default=False, help_text='Show website portfolio section'),
        ),
        migrations.CreateModel(
            name='WebsitePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Full URL of the website to showcase')),
                ('title', models.CharField(help_text='Project or website name', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Brief description', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_portfolios', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
