# Generated by Django 6.0.2 on 2026-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_show_website_portfolio_websiteportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
