# Generated by Django 6.0.2 on 2026-03-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_contact_message_sender_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='sender_phone',
            field=models.CharField(max_length=30),
        ),
    ]
