# Generated by Django 6.0.2 on 2026-03-11 08:57

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_contact_message_phone_required_message_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_code',
            field=models.CharField(blank=True, default=profiles.models.generate_profile_code, help_text='Unique code used in the NFC card subdomain URL', max_length=10),
        ),
    ]
