# Generated by Django 6.0.2 on 2026-03-11 08:59

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profile_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_code',
            field=models.CharField(blank=True, default=profiles.models.generate_profile_code, help_text='Unique code used in the NFC card subdomain URL', max_length=10, unique=True),
        ),
    ]
