# Generated by Django 6.0.2 on 2026-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_profile_profile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Auto-generated QR code for NFC card', upload_to='qr_codes/'),
        ),
    ]
