# Generated by Django 6.0.2 on 2026-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_add_qr_code_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('author_role', models.CharField(help_text='e.g. CEO at Acme Inc.', max_length=150)),
                ('author_company', models.CharField(blank=True, max_length=150)),
                ('author_photo', models.ImageField(help_text='Profile photo of the author', upload_to='homepage/testimonials/')),
                ('content', models.TextField(help_text='Testimonial content', max_length=1000)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1-5 star rating')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Testimonial',
                'verbose_name_plural': 'Homepage Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
