# Generated by Django 6.0.2 on 2026-02-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(default='#2EC4B6', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(default='#6B2FA0', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text_color',
            field=models.CharField(default='#1E293B', max_length=7),
        ),
    ]
