[uwsgi]
# full path to Django project's root directory
chdir            = /home/cardava_tech/infinity_card/
# Django's wsgi file
module           = infinity_cards.wsgi
# full path to python virtual env
home             = /home/cardava_tech/infinity_card/venv

# enable uwsgi master process
master          = true
# maximum number of worker processes
processes       = 10
# the socket (use the full path to be safe)
socket          = /home/cardava_tech/infinity_card/infinity_card.sock
# socket permissions
chmod-socket    = 666
# clear environment on exit
vacuum          = true
# daemonize the process and send logs to file
daemonize       = /home/cardava_tech/infinity_card/uwsgi-emperor.log
