# Generated by Django 6.0.2 on 2026-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reviewer name (e.g. "Daniel M.")', max_length=100)),
                ('review', models.TextField(help_text='Review text shown in the modal')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Star rating 1-5')),
                ('date_label', models.CharField(blank=True, help_text='Display date (e.g. "02/2026")', max_length=20)),
                ('thumbnail', models.ImageField(help_text='Portrait thumbnail image for the carousel slide', upload_to='testimonials/thumbnails/')),
                ('video_source', models.CharField(choices=[('upload', 'Upload Video'), ('link', 'External Link')], default='upload', max_length=10)),
                ('video_file', models.FileField(blank=True, help_text='Upload an MP4 video file', upload_to='testimonials/videos/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Show verified badge')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
