# Generated by Django 6.0.2 on 2026-02-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapevent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_events', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='tapevent',
            index=models.Index(fields=['profile', '-timestamp'], name='analytics_t_profile_f6ef12_idx'),
        ),
    ]
