# Generated by Django 6.0.2 on 2026-02-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('profiles', '0008_profile_show_bio_profile_show_business_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('profile_view', 'Profile View'), ('catalog_view', 'Catalog Page View'), ('product_click', 'Product Click'), ('catalog_seeall', 'Catalog See All Click'), ('contact_click', 'Contact Click'), ('social_click', 'Social Link Click'), ('website_click', 'Website Click')], max_length=30)),
                ('item_id', models.PositiveIntegerField(blank=True, help_text='Related catalog item ID', null=True)),
                ('item_title', models.CharField(blank=True, help_text='Snapshot of item title at event time', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_events', to='profiles.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['profile', 'event_type', '-timestamp'], name='analytics_p_profile_0213fd_idx'), models.Index(fields=['profile', '-timestamp'], name='analytics_p_profile_c4692f_idx')],
            },
        ),
    ]
