# Generated by Django 6.0.2 on 2026-03-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('personal', 'Personal / Individual'), ('business', 'Business')], default='', help_text='Selected during onboarding: personal or business', max_length=10),
        ),
    ]
