# Generated by Django 6.0.2 on 2026-03-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code (e.g., ZW for Zimbabwe)', max_length=2),
        ),
    ]
