# Generated by Django 6.0.2 on 2026-03-14 18:00

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Select your country', max_length=2),
        ),
    ]
