"""
Django settings for infinity_cards project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-a&h!(m1%__%5#%4i(d!=(#*yf@s3dg!0r0fxy75tbgo0l5w$aj')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Allow all hosts in development, restrict in production via env var
_allowed_hosts = os.environ.get('ALLOWED_HOSTS', '')
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['*'] if DEBUG else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # Third-party apps
    'django_countries',
    # Project apps
    'accounts',
    'profiles',
    'categories',
    'cards',
    'subscriptions',
    'themes',
    'analytics',
    'core',
    'companies',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.DevCsrfTrustedOriginMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # Custom
    'accounts.middleware.OnboardingMiddleware',
    'core.middleware.SubdomainMiddleware',
    'subscriptions.middleware.SubscriptionMiddleware',
]

ROOT_URLCONF = 'infinity_cards.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.subscription_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'infinity_cards.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'infinitycards',
        'USER': 'postgres',
        'PASSWORD': '@saratobi97',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Sites framework (required by allauth)
SITE_ID = 1

# Auth redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/signup/account-type/'
LOGOUT_REDIRECT_URL = '/'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ── django-allauth settings ──
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_SIGNUP_REDIRECT_URL = '/signup/account-type/'
ACCOUNT_LOGIN_REDIRECT_URL = '/signup/account-type/'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# ── Email ──
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.inftycard.cc'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'no-reply@inftycard.cc'
EMAIL_HOST_PASSWORD = 'pass2026'
DEFAULT_FROM_EMAIL = 'InfinityCard <no-reply@inftycard.cc>'
SERVER_EMAIL = 'no-reply@inftycard.cc'

ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapter.CustomSocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
}

# CSRF trusted origins
# Port wildcards (http://127.0.0.1:*) don't work in Django 4+; only subdomain wildcards do.
# In DEBUG mode we use middleware to trust any localhost origin (ports change every restart).
CSRF_TRUSTED_ORIGINS = [
    'https://*.inftycard.cc',
    'https://inftycard.cc',
]

# Security headers (spec §10)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Default primary key type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Rate limiting cache backend
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# ── Logging ──
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '%(levelname)s %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'loggers': {
        'subscriptions': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False},
    },
}

# ── PayPal Subscriptions API ──
# Set these via environment variables in production.
PAYPAL_MODE = os.environ.get('PAYPAL_MODE', 'sandbox')  # 'sandbox' or 'live'
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', 'AbJvvK2xJ-7E2KGunouNG65iNsW0_ZBEOsCcU3tTwugQR6pwEBqBA2Gw73B2d5dmyOAVUDBn_E86idGh')
PAYPAL_SECRET = os.environ.get('PAYPAL_SECRET', 'EOIFgnMHQMsWGUXVBfC_BzTvPc8YSmORlOgwUP68KyTOjgOW65E427ShYKRVEyRk8erSZCQeyuSnt04A')
PAYPAL_API_BASE = (
    'https://api-m.sandbox.paypal.com' if PAYPAL_MODE == 'sandbox'
    else 'https://api-m.paypal.com'
)

# ── Development: skip PayPal for quick testing ──
# Set to False (or remove) in production to require real PayPal payments.
DEV_SKIP_PAYPAL = False  # Production mode: enforce real PayPal payments

# ── Bank Transfer Details ──
# Banking details are now managed dynamically via the admin dashboard
# (BankingDetail model in subscriptions app). See /manage/banking-details/

# ── EcoCash (direct API — credentials to be configured when API access is granted) ──
ECOCASH_API_URL = os.environ.get('ECOCASH_API_URL', '')
ECOCASH_MERCHANT_ID = os.environ.get('ECOCASH_MERCHANT_ID', '')
ECOCASH_MERCHANT_KEY = os.environ.get('ECOCASH_MERCHANT_KEY', '')

ECOCASH_DETAILS = {
    'merchant_name': 'InfinityCard Technologies',
    'merchant_number': '0771 000 000',
    'merchant_code': '*151*2*1#',
}

# ── Card Design ──
CUSTOM_DESIGN_FEE = float(os.environ.get('CUSTOM_DESIGN_FEE', '25.00'))

# ── Celery + Redis ──
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
