# Generated by Django 6.0.2 on 2026-02-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativemedia',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_packages', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='realestateproperty',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='profiles.profile'),
        ),
    ]
