# Generated by Django 6.0.2 on 2026-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_bg',
            field=models.CharField(blank=True, help_text='CSS background for icon container, e.g. rgba(99,102,241,.15)', max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_color',
            field=models.CharField(blank=True, help_text='CSS color for the icon SVG stroke, e.g. #A5B4FC', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, help_text='SVG inner markup (path elements) for the category icon'),
        ),
    ]
