# Generated by Django 6.0.2 on 2026-03-01 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_cardorder_custom_design_fee_cardorder_design_back_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly company identifier', unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, help_text='Company billing/physical address')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Company contact email', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='The user who registered this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Company Admin'), ('employee', 'Employee')], default='employee', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('invite_email', models.EmailField(help_text='Email the invite was sent to', max_length=254)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('employee_name', models.CharField(blank=True, help_text='Full name for the card', max_length=200)),
                ('employee_title', models.CharField(blank=True, help_text='Job title for the card', max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
                ('user', models.ForeignKey(blank=True, help_text='Set once the user accepts the invite or is created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'role', 'employee_name'],
                'unique_together': {('company', 'invite_email')},
            },
        ),
        migrations.CreateModel(
            name='BulkCardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of cards to order')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custom_design_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('design_option', models.CharField(choices=[('upload', 'Company Uploads Design'), ('custom', 'Request Custom Design'), ('individual', 'Each Employee Uploads Own')], default='upload', max_length=10)),
                ('design_front', models.ImageField(blank=True, upload_to='company_designs/')),
                ('design_back', models.ImageField(blank=True, upload_to='company_designs/')),
                ('design_notes', models.TextField(blank=True)),
                ('shipping_company_name', models.CharField(blank=True, max_length=200)),
                ('shipping_contact_name', models.CharField(blank=True, max_length=200)),
                ('shipping_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_phone', models.CharField(blank=True, max_length=30)),
                ('shipping_address1', models.CharField(blank=True, max_length=255)),
                ('shipping_address2', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_zip', models.CharField(blank=True, max_length=20)),
                ('shipping_country', models.CharField(blank=True, default='United States', max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('tracking_url', models.URLField(blank=True)),
                ('paypal_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('card_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_orders', to='cards.nfccardproduct')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_orders_placed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_orders', to='companies.company')),
                ('members', models.ManyToManyField(blank=True, help_text='Employees included in this order', related_name='bulk_orders', to='companies.companymembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
