# Generated by Django 6.0.2 on 2026-03-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cardorder_custom_design_fee_cardorder_design_back_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='unassigned', max_length=15)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_assignments', to='companies.bulkcardorder')),
                ('card_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_assignments', to='cards.nfccardproduct')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to='companies.company')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_assignments', to='companies.companymembership')),
                ('nfc_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assignment', to='cards.nfccard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
