# Generated by Django 6.0.2 on 2026-03-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companybillingevent_companysubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcardorder',
            name='design_option',
            field=models.CharField(choices=[('standard', 'InfinityCard Branded'), ('custom', 'Custom Branded')], default='standard', max_length=10),
        ),
    ]
