# Generated by Django 6.0.2 on 2026-03-02 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_update_bulkcardorder_design_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcardorder',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash')], default='paypal', max_length=20),
        ),
        migrations.CreateModel(
            name='ProofOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('document', models.ImageField(help_text='Screenshot or photo of payment confirmation', upload_to='proof_of_payment/%Y/%m/')),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference or EcoCash transaction ID', max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount transferred', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date the payment was made')),
                ('notes', models.TextField(blank=True, help_text='Additional details about the payment')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_payments', to='companies.bulkcardorder')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_reviews', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
