# Generated by Django 6.0.2 on 2026-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_bulkcardorder_payment_method_proofofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcardorder',
            name='ecocash_phone',
            field=models.CharField(blank=True, help_text='EcoCash phone number used for payment', max_length=20),
        ),
    ]
