# Generated by Django 6.0.2 on 2026-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_bulkcardorder_ecocash_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='ecocash_phone',
            field=models.CharField(blank=True, help_text='EcoCash phone used for subscription payment', max_length=20),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='num_cards',
            field=models.PositiveIntegerField(default=1, help_text='Number of NFC cards billed for'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash')], default='paypal', max_length=20),
        ),
    ]
