# Generated by Django 6.0.2 on 2026-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companysubscription_ecocash_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
    ]
