# Generated by Django 6.0.2 on 2026-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcardorder',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for declining a cash payment'),
        ),
        migrations.AlterField(
            model_name='bulkcardorder',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash'), ('cash', 'Cash Payment')], default='paypal', max_length=20),
        ),
    ]
