# Generated by Django 6.0.2 on 2026-02-27 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='badge_label',
            field=models.CharField(blank=True, help_text='e.g., "Popular", "Best Value"', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, help_text='Short marketing description'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Visually emphasize on pricing page'),
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subscribe', 'New Subscription'), ('upgrade', 'Plan Upgrade'), ('downgrade', 'Plan Downgrade'), ('renew', 'Renewal'), ('cancel', 'Cancellation')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
