# Generated by Django 6.0.2 on 2026-03-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_paypal_plan_id_plan_paypal_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paypal_yearly_plan_id',
            field=models.CharField(blank=True, help_text='PayPal Yearly Billing Plan ID', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_discount_percent',
            field=models.PositiveIntegerField(default=20, help_text='Discount percentage for yearly billing (e.g. 20 = 20% off)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Monthly or yearly billing cycle', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, help_text='PayPal Monthly Billing Plan ID', max_length=100),
        ),
    ]
