# Generated by Django 6.0.2 on 2026-03-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_plan_paypal_yearly_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ecocash_phone',
            field=models.CharField(blank=True, help_text='EcoCash phone used for subscription payment', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash')], default='paypal', max_length=20),
        ),
    ]
