# Generated by Django 6.0.2 on 2026-03-02 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Billing period for the pending plan change', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, help_text='Plan the user will switch to at end of current billing period (scheduled downgrade)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='subscriptions.plan'),
        ),
    ]
