# Generated by Django 6.0.2 on 2026-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_pending_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Internal notes about this payment method')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method Setting',
                'verbose_name_plural': 'Payment Method Settings',
                'ordering': ['method'],
            },
        ),
    ]
