# Generated by Django 6.0.2 on 2026-03-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_paymentmethodsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, max_length=150)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show this account to customers')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary account shown first')),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banking Detail',
                'verbose_name_plural': 'Banking Details',
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
        migrations.AlterField(
            model_name='paymentmethodsettings',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash'), ('cash', 'Cash Payment')], max_length=20, unique=True),
        ),
    ]
