# Generated by Django 6.0.2 on 2026-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_banking_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='display_features',
            field=models.JSONField(blank=True, default=list, help_text='List of {"text": "...", "included": true/false} for homepage pricing display'),
        ),
        migrations.AddField(
            model_name='plan',
            name='subtitle',
            field=models.CharField(blank=True, help_text='e.g., "For individuals", "For growing teams"', max_length=100),
        ),
    ]
