# Generated by Django 6.0.2 on 2026-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
