# Generated by Django 6.0.2 on 2026-03-01 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCCardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('material', models.CharField(choices=[('plastic', 'Plastic'), ('plastic_gold', 'Plastic Gold'), ('plastic_transparent', 'Plastic Transparent'), ('wood', 'Wood'), ('metal', 'Metal')], max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='One-time purchase price in USD', max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='card_products/')),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='CardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('channel', models.CharField(choices=[('online', 'Online (PayPal)'), ('physical', 'Physical / In-Person'), ('admin', 'Admin Manual')], default='online', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paypal_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('subscription_activated', models.BooleanField(default=False, help_text='Whether monthly subscription was activated after purchase')),
                ('shipping_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_orders', to=settings.AUTH_USER_MODEL)),
                ('card_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cards.nfccardproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
