# Generated by Django 6.0.2 on 2026-03-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_nfccardproduct_cardorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardorder',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='cardorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 2 (apt, suite, etc.)'),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_country',
            field=models.CharField(blank=True, default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State / Province'),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='shipping_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='ZIP / Postal code'),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=200),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Tracking URL for the shipment'),
        ),
    ]
