# Generated by Django 6.0.2 on 2026-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_cardorder_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorder',
            name='custom_design_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra charge for custom design', max_digits=6),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='design_back',
            field=models.ImageField(blank=True, help_text='Back design uploaded by user', upload_to='card_designs/'),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='design_front',
            field=models.ImageField(blank=True, help_text='Front design uploaded by user', upload_to='card_designs/'),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='design_notes',
            field=models.TextField(blank=True, help_text='Instructions for custom design (name, title, colors, etc.)'),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='design_option',
            field=models.CharField(choices=[('upload', 'User Uploads Own Design'), ('custom', 'Request Custom Design from Platform')], default='upload', max_length=10),
        ),
    ]
