# Generated by Django 6.0.2 on 2026-03-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cardorder_custom_design_fee_cardorder_design_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccardproduct',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custom branded card price in USD (0 = not available)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='nfccardproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Standard InfinityCard price in USD', max_digits=6),
        ),
    ]
