# Generated by Django 6.0.2 on 2026-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_add_custom_price_to_nfccardproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardorder',
            name='design_option',
            field=models.CharField(choices=[('standard', 'InfinityCard Branded'), ('custom', 'Custom Branded')], default='standard', max_length=10),
        ),
    ]
