# Generated by Django 6.0.2 on 2026-03-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_add_payment_method_and_pop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='card_products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image shown as the main product photo')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cards.nfccardproduct')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', '-created_at'],
            },
        ),
    ]
